# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f3680de13b86c0e1a78e25e77e026ffe9980f4fbe3cce1f2ef13e792c3548f41b8706fa80e1526eb69df88a0da4a7f108129866c8861412a03d4801990ba589

test:
  secret_key_base: a8fcda3ab7da0a373713713dc3b40b910687f62630a23312be4e6f35aed08f354ddf22dca361a18af50880e10852993747e0200d9165980326bda56680e1731e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
